/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_GRSIM_COMMANDS_PB_H_INCLUDED
#define PB_GRSIM_COMMANDS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _grSim_Commands { 
    double timestamp; 
    bool isteamyellow; 
    pb_callback_t robot_commands; 
} grSim_Commands;

typedef struct _grSim_Robot_Command { 
    uint32_t id; 
    float kickspeedx; 
    float kickspeedz; 
    float veltangent; 
    float velnormal; 
    float velangular; 
    bool spinner; 
    bool wheelsspeed; 
    bool has_wheel1;
    float wheel1; 
    bool has_wheel2;
    float wheel2; 
    bool has_wheel3;
    float wheel3; 
    bool has_wheel4;
    float wheel4; 
} grSim_Robot_Command;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define grSim_Robot_Command_init_default         {0, 0, 0, 0, 0, 0, 0, 0, false, 0, false, 0, false, 0, false, 0}
#define grSim_Commands_init_default              {0, 0, {{NULL}, NULL}}
#define grSim_Robot_Command_init_zero            {0, 0, 0, 0, 0, 0, 0, 0, false, 0, false, 0, false, 0, false, 0}
#define grSim_Commands_init_zero                 {0, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define grSim_Commands_timestamp_tag             1
#define grSim_Commands_isteamyellow_tag          2
#define grSim_Commands_robot_commands_tag        3
#define grSim_Robot_Command_id_tag               1
#define grSim_Robot_Command_kickspeedx_tag       2
#define grSim_Robot_Command_kickspeedz_tag       3
#define grSim_Robot_Command_veltangent_tag       4
#define grSim_Robot_Command_velnormal_tag        5
#define grSim_Robot_Command_velangular_tag       6
#define grSim_Robot_Command_spinner_tag          7
#define grSim_Robot_Command_wheelsspeed_tag      8
#define grSim_Robot_Command_wheel1_tag           9
#define grSim_Robot_Command_wheel2_tag           10
#define grSim_Robot_Command_wheel3_tag           11
#define grSim_Robot_Command_wheel4_tag           12

/* Struct field encoding specification for nanopb */
#define grSim_Robot_Command_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   id,                1) \
X(a, STATIC,   REQUIRED, FLOAT,    kickspeedx,        2) \
X(a, STATIC,   REQUIRED, FLOAT,    kickspeedz,        3) \
X(a, STATIC,   REQUIRED, FLOAT,    veltangent,        4) \
X(a, STATIC,   REQUIRED, FLOAT,    velnormal,         5) \
X(a, STATIC,   REQUIRED, FLOAT,    velangular,        6) \
X(a, STATIC,   REQUIRED, BOOL,     spinner,           7) \
X(a, STATIC,   REQUIRED, BOOL,     wheelsspeed,       8) \
X(a, STATIC,   OPTIONAL, FLOAT,    wheel1,            9) \
X(a, STATIC,   OPTIONAL, FLOAT,    wheel2,           10) \
X(a, STATIC,   OPTIONAL, FLOAT,    wheel3,           11) \
X(a, STATIC,   OPTIONAL, FLOAT,    wheel4,           12)
#define grSim_Robot_Command_CALLBACK NULL
#define grSim_Robot_Command_DEFAULT NULL

#define grSim_Commands_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, DOUBLE,   timestamp,         1) \
X(a, STATIC,   REQUIRED, BOOL,     isteamyellow,      2) \
X(a, CALLBACK, REPEATED, MESSAGE,  robot_commands,    3)
#define grSim_Commands_CALLBACK pb_default_field_callback
#define grSim_Commands_DEFAULT NULL
#define grSim_Commands_robot_commands_MSGTYPE grSim_Robot_Command

extern const pb_msgdesc_t grSim_Robot_Command_msg;
extern const pb_msgdesc_t grSim_Commands_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define grSim_Robot_Command_fields &grSim_Robot_Command_msg
#define grSim_Commands_fields &grSim_Commands_msg

/* Maximum encoded size of messages (where known) */
/* grSim_Commands_size depends on runtime parameters */
#define grSim_Robot_Command_size                 55

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
